require("plugins.blink")
-- require("plugins.yazi")
-- require("plugins.fff")
require("plugins.whichkey")
require("plugins.neogit")
require("plugins.oil")
require("plugins.mason")
require("plugins.conform")
require("plugins.snacks")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.color")
-- require("plugins.whichkey")
